In [ ]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:

df=pd.read_csv('/content/winequality.csv')
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           8.94             0.507         0.29            0.90      0.031   
1           8.42             0.681         0.19            3.33      0.012   
2           9.65             0.362         0.35            2.24      0.159   
3           5.63             0.278         0.50            0.90      0.099   
4           6.49             0.474         0.59            6.77      0.142   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  7.8                  21.9   0.9993  3.44       0.62   
1                  1.0                  53.6   0.9953  3.36       1.10   
2                 21.4                  62.2   0.9968  3.46       0.68   
3                  6.3                  19.1   0.9952  3.50       0.72   
4                 19.3                  44.9   0.9972  3.41       0.67   

   alcohol  quality  
0     9.89        5  
1    11.77        6  
2     9.69        5 

In [ ]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape: (1607, 12)

Columns:
Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

Data Types:
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

Missing Values:
fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides               12
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                      15
sulphates               19
alcohol                  0
quality              

In [ ]:
imputer = SimpleImputer(strategy='median')

df[['chlorides', 'pH', 'sulphates']] = imputer.fit_transform(
    df[['chlorides', 'pH', 'sulphates']]
)

print(df.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


In [ ]:
X = df.drop('quality', axis=1)

y = df['quality']

print(X.head())
print(y.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           8.94             0.507         0.29            0.90      0.031   
1           8.42             0.681         0.19            3.33      0.012   
2           9.65             0.362         0.35            2.24      0.159   
3           5.63             0.278         0.50            0.90      0.099   
4           6.49             0.474         0.59            6.77      0.142   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  7.8                  21.9   0.9993  3.44       0.62   
1                  1.0                  53.6   0.9953  3.36       1.10   
2                 21.4                  62.2   0.9968  3.46       0.68   
3                  6.3                  19.1   0.9952  3.50       0.72   
4                 19.3                  44.9   0.9972  3.41       0.67   

   alcohol  
0     9.89  
1    11.77  
2     9.69  
3    10.90  
4    11.01  
0    5
1

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.1,
    random_state=42,
    stratify=y
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (1446, 11)
Testing Data Shape: (161, 11)


In [24]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [37]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [38]:
train_pred = model.predict(X_train) + min_quality_score
test_pred = model.predict(X_test) + min_quality_score

In [55]:
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

train_acc = accuracy_score(y_train, train_pred)
test_acc = accuracy_score(y_test, test_pred)

print("Training Accuracy:", train_acc)
print("Testing Accuracy:", test_acc)
print("Gap:", train_acc - test_acc)

Training Accuracy: 0.6514522821576764
Testing Accuracy: 0.5279503105590062
Gap: 0.12350197159867016


In [54]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           4       0.00      0.00      0.00         8
           5       0.52      0.52      0.52        64
           6       0.54      0.68      0.60        76
           7       0.00      0.00      0.00        13

    accuracy                           0.53       161
   macro avg       0.26      0.30      0.28       161
weighted avg       0.46      0.53      0.49       161



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [53]:
print(confusion_matrix(y_test, test_pred))

[[ 0  7  1  0]
 [ 0 33 31  0]
 [ 0 24 52  0]
 [ 0  0 13  0]]


In [52]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

                 Feature  Importance
10               alcohol    0.410787
1       volatile acidity    0.122383
4              chlorides    0.103339
9              sulphates    0.068880
5    free sulfur dioxide    0.050277
6   total sulfur dioxide    0.045746
8                     pH    0.042213
3         residual sugar    0.042051
0          fixed acidity    0.041325
2            citric acid    0.038845
7                density    0.034154


In [51]:
sample = X_test[0].reshape(1, -1)

prediction = model.predict(sample)

print("Predicted Quality:", prediction[0])
print("Actual Quality:", y_test.iloc[0])

Predicted Quality: 6
Actual Quality: 6


In [50]:
predictions = model.predict(X_test[:10])

for i in range(10):
    print("Actual:", y_test.iloc[i], "| Predicted:", predictions[i])

Actual: 6 | Predicted: 6
Actual: 5 | Predicted: 5
Actual: 6 | Predicted: 5
Actual: 5 | Predicted: 5
Actual: 6 | Predicted: 5
Actual: 6 | Predicted: 6
Actual: 5 | Predicted: 5
Actual: 6 | Predicted: 6
Actual: 5 | Predicted: 6
Actual: 5 | Predicted: 5


In [49]:
new_wine = pd.DataFrame({
    'fixed acidity':[7.4],
    'volatile acidity':[0.70],
    'citric acid':[0.00],
    'residual sugar':[1.9],
    'chlorides':[0.076],
    'free sulfur dioxide':[11.0],
    'total sulfur dioxide':[34.0],
    'density':[0.9978],
    'pH':[3.51],
    'sulphates':[0.56],
    'alcohol':[9.4]
})

new_wine_scaled = scaler.transform(new_wine)

prediction = model.predict(new_wine_scaled)

print("Predicted Wine Quality:", prediction[0])

Predicted Wine Quality: 5
